### ISSUE TITLE
Review of week 01 homework

### ISSUE THREAD

**Issue by jakub-c** [jakub-c/hyf-html-css-lecture-structure#1]
Suggestions for the review:

* please write which homework you'll review - to avoid stepping on each othe's toes
* I suggest annotating particular lines of code on Github and opening issues per line - [example](https://github.com/ShazaMaher/week-01/issues/9)
* pro tip: if you highlight a line on github - you can press shift and select multiple lines in case you want to talk about bigger piece of the code - [example](https://github.com/ShazaMaher/week-01/issues/2)
* areas worth looking into:
  * semantic HTML
  * style (indentations)
  * if the submission looks like the [assignment](https://github.com/jakub-c/hyf-html-css-lecture-structure/blob/master/week-01/week-01-homework.pdf)
  * and any other areas you find relevant

This is the list of homework submissions that I got from the Slack channel:

|                |                                                                   | J                                                                                                 | Z                                                              |
| -------------- | ----------------------------------------------------------------- | ------------------------------------------------------------------------------------------------- | -------------------------------------------------------------- |
| Anowar         | https://github.com/smauddin/hyf-html-css/tree/master/week1        | [rev](https://github.com/smauddin/hyf-html-css/issues/1)                                          |                                                                |
| Chandu         | https://github.com/chandu87/HYF-HTML-CSS/tree/master/week1        | validator warning                                                                                 |                                                                |
| Hossein        | https://github.com/hosseinz/hyf-html-css                          | [rev](https://github.com/hosseinz/hyf-html-css/issues?utf8=%E2%9C%93&q=is%3Aissue+week+01)        |                                                                |
| Siri           | https://github.com/Siri93/hyf-homework-/tree/master/week1         | [rev](https://github.com/Siri93/hyf-homework-/issues/1)                                           |                                                                |
| Shaza          | https://github.com/ShazaMaher/week-01                             | [rev](https://github.com/ShazaMaher/week-01/issues)                                               |                                                                |
| Saqib          | https://github.com/chsaqib/hyf-html-css/tree/master/week1         |                                                                                                   | [rev](https://github.com/chsaqib/hyf-html-css/issues/1)        |
| Amrita         | https://github.com/AmritaMaloo/Week01-html-css/tree/master/feb-25 |                                                                                                   | [rev](https://github.com/AmritaMaloo/Week01-html-css/issues/1) |
| Behnam         | https://github.com/Behnam07/homework1                             | [rev](https://github.com/Behnam07/homework1/issues?utf8=%E2%9C%93&q=is%3Aissue+week+01+)          |                                                                |
| Liaqut         | https://github.com/lial80/hyf-html-css                            | [rev](https://github.com/lial80/hyf-html-css/issues?utf8=%E2%9C%93&q=is%3Aissue+week+01)          |                                                                |
| Richard        | https://github.com/paredesrichard/hyf-html-css/tree/master/week1  |                                                                                                   | [rev](https://github.com/paredesrichard/hyf-html-css/issues/1) |
| Hedayat        | https://github.com/Hedayatsamadi123/hyf-html-css                  | [rev](https://github.com/Hedayatsamadi123/hyf-html-css/issues?utf8=%E2%9C%93&q=is%3Aissue+week01) |                                                                |
| Mekkan         | https://github.com/majidkhan/HYF-CPH/tree/master/week1            | [rev](https://github.com/majidkhan/HYF-CPH/issues/1)                                              |                                                                |
| Badar          | https://github.com/bader508/badar                                 | [rev](https://github.com/bader508/badar/issues/1)                                                 |                                                                |
| Jackline       | https://github.com/jacklinenassozi/finalhomework                  | [rev](https://github.com/jacklinenassozi/finalhomework/issues/1)                                  |                                                                |
| Manuel         | https://github.com/manuelongareno/hyf.week01.                     | [rev](https://github.com/manuelongareno/hyf.week01./issues?utf8=%E2%9C%93&q=is%3Aissue+week+01)   |                                                                |
| A.haseeb.safay | https://hsafay.github.io/class05cvhaseeb/                         | [rev](https://github.com/hsafay/class05cvhaseeb/issues?utf8=%E2%9C%93&q=is%3Aissue+week+01)       |                                                                |

**Comment by zkwsk** [comment]
I'll grab the remaining ones :)

**Comment by zkwsk** [comment]
@jakub-c What did you do to those with validator errors? Did you just tell them to fix it or did you give them some feedback?

**Comment by zkwsk** [comment]
Just reviewed Saqib's submission: https://github.com/chsaqib/hyf-html-css/issues/1

**Comment by zkwsk** [comment]
Amrita's feedback https://github.com/AmritaMaloo/Week01-html-css/issues/1

**Comment by jakub-c** [comment]
@zkwsk on validator error - I skip the review and notify the student that fixes are needed

**Comment by zkwsk** [comment]
Richards review. I won't be able to do more before class, so we'd have to do any remaining reviews after.
