### ISSUE TITLE
Review of week 02 homework

### ISSUE THREAD

**Issue by jakub-c** [jakub-c/hyf-html-css-lecture-structure#3]
Suggestions for the review:

* please write which homework you'll review - to avoid stepping on each othe's toes
* I suggest annotating particular lines of code on Github and opening issues per line - [example](https://github.com/ShazaMaher/week-01/issues/9)
* pro tip: if you highlight a line on github - you can press shift and select multiple lines in case you want to talk about bigger piece of the code - [example](https://github.com/ShazaMaher/week-01/issues/2)
* areas worth looking into:
  * semantic HTML
  * style (indentations)
  * if the submission looks like the [assignment](https://github.com/jakub-c/hyf-html-css-lecture-structure/blob/master/week02/assignments/week-02-homework.jpg) and the [mobile wireframe](https://github.com/jakub-c/hyf-html-css-lecture-structure/blob/master/week02/assignments/week-02-homework-mobile-view.jpg) - I think it is important that we make students aware that it is very important to follow the designs the way they are
  * and any other areas you find relevant

This is the list of homework submissions that I got from the Slack channel:

|          |                                                                                                                                                            |                                                                                                   |
| -------- | ---------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------- |
| Richard  | [repo](https://github.com/paredesrichard/hyf-html-css/tree/master/week2/homework) [preview](https://paredesrichard.github.io/hyf-html-css/week2/homework/) | Zaki - in progess                                                                                 |
| Anowar   | [repo](https://github.com/smauddin/hyf-html-css/tree/master/week2) [preview](https://smauddin.github.io/hyf-html-css/week2/)                               | Zaki - in progess                                                                                 |
| Hedayat  | [repo](https://github.com/Hedayatsamadi123/hyf-html-css/tree/master/week02) [preview](https://hedayatsamadi123.github.io/hyf-html-css/week02/)             | Zaki - in progess                                                                                 |
| Amrita   | [repo](https://github.com/AmritaMaloo/hyf-html-css/tree/master/mar-04) [preview](https://amritamaloo.github.io/hyf-html-css/mar-04/)                       | Zaki - in progess                                                                                 |
| Chandu   | [repo](https://github.com/chandu87/HYF-HTML-CSS/tree/master/week2) [preview](https://chandu87.github.io/HYF-HTML-CSS/week2/)                               | Jakub [rev](https://github.com/chandu87/HYF-HTML-CSS/issues?utf8=%E2%9C%93&q=is%3Aissue+week+02+) |
| Jackline | [repo](https://github.com/jacklinenassozi/homework.week2/blob/master/index.html) [preview](https://jacklinenassozi.github.io/homework.week2/)              | ⚠️ validator warnings                                                                             |
| Bader    | [repo](https://github.com/bader508/badar)                                                                                                                  | Jakub [rev](https://github.com/bader508/badar/issues?utf8=%E2%9C%93&q=is%3Aissue+week+02)         |
| Saqib    | [repo](https://github.com/chsaqib/hyf-html-css/tree/master/week2) [preview](https://chsaqib.github.io/hyf-html-css/week2/)                                 | Jakub [rev](https://github.com/chsaqib/hyf-html-css/issues?utf8=%E2%9C%93&q=is%3Aissue+week+03)   |
| Makkan   | [repo](https://github.com/majidkhan/HYF-CPH/tree/master/03-mar-2018/week2-homework)                                                                        | Benna - in progess                                                                                |
| Shaza    | [repo](https://github.com/ShazaMaher/hyf-html-css-week-02)                                                                                                 | Benna - in progess                                                                                |
| Siri     | [repo](https://github.com/Siri93/hyf-week-2/blob/master/week2/index2.html)                                                                                 | Benna - in progess                                                                                |
| Hossein  | [repo](https://github.com/hosseinz/hyf-html-css/tree/master/week2) [preview](https://hosseinz.github.io/hyf-html-css/week2/)                               | Benna - in progess                                                                                |
| Liaqut   | [repo](https://github.com/lial80/week-2-/tree/master/assignment-2)                                                                                         | Benna - in progess                                                                                |

**Comment by ShazaMaher** [comment]
@jakub-c  did you ask me to review the homeworks with you?

**Comment by zkwsk** [comment]
I'll grab the first 4.

**Comment by jakub-c** [comment]
I'll take the next 4

**Comment by benna100** [comment]
I'll take the rest

**Comment by jakub-c** [comment]
@zkwsk @benna100 please ping me when you're done with the reviews - I'll update the links and close it than. Thanks.

**Comment by zkwsk** [comment]
@jakub-c @benna100 I won't be able to do the reviews until tonight or tomorrow morning, but I'll be at class to say a few words about the homework feedback, so if you will give me a brief recap of any recurrent themes in the feedback it will be much appreciated.

**Comment by jakub-c** [comment]
@zkwsk @benna100 - a small follow up. Should I close this issue?

**Comment by jakub-c** [comment]
based on the slack conversation my understanding that week 02 review has been done in person for those people that don't have related issues created in their repos - therefore I'm closing this.
